export enum NotificationType {
  REGISTRATION = 'REGISTRATION',
  DOCUMENT = 'DOCUMENT',
  BIOMETRIC = 'BIOMETRIC',
  VERIFICATION = 'VERIFICATION',
  APPROVAL = 'APPROVAL',
  REJECTION = 'REJECTION',
  SYSTEM = 'SYSTEM'
} 