-- Drop existing tables if they exist
DROP TABLE IF EXISTS nida_verifications;
DROP TABLE IF EXISTS nida;

-- Create nida table with proper constraints
CREATE TABLE nida (
    nida_number VARCHAR(255) PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    middle_name VARCHAR(255),
    last_name VARCHAR(255) NOT NULL,
    other_names VARCHAR(255),
    date_of_birth DATE NOT NULL,
    nationality VARCHAR(255) NOT NULL,
    biometric_data TEXT,
    phone_number VARCHAR(255),
    gender VARCHAR(50) NOT NULL,
    marital_status VARCHAR(50),
    occupation VARCHAR(255),
    employer_name VARCHAR(255),
    dossier_number VARCHAR(255),
    employment_status VARCHAR(50),
    birth_certificate_number VARCHAR(255),
    father_first_name VARCHAR(255),
    father_middle_name VARCHAR(255),
    father_last_name VARCHAR(255),
    father_birth_country VARCHAR(255),
    father_date_of_birth VARCHAR(255),
    mother_first_name VARCHAR(255),
    mother_middle_name VARCHAR(255),
    mother_last_name VARCHAR(255),
    mother_birth_country VARCHAR(255),
    mother_date_of_birth VARCHAR(255),
    citizenship_type VARCHAR(50),
    naturalization_certificate_number VARCHAR(255),
    birth_country VARCHAR(255) NOT NULL,
    birth_region VARCHAR(255) NOT NULL,
    birth_district VARCHAR(255) NOT NULL,
    birth_ward VARCHAR(255) NOT NULL,
    current_residence_house_number VARCHAR(255) NOT NULL,
    current_residence_region VARCHAR(255) NOT NULL,
    current_residence_postal_code VARCHAR(255) NOT NULL,
    current_residence_district VARCHAR(255) NOT NULL,
    current_residence_ward VARCHAR(255) NOT NULL,
    current_residence_village VARCHAR(255) NOT NULL,
    current_residence_street VARCHAR(255) NOT NULL,
    current_residence_postal_box VARCHAR(255) NOT NULL,
    permanent_residence_house_number VARCHAR(255) NOT NULL,
    permanent_residence_region VARCHAR(255) NOT NULL,
    permanent_residence_postal_code VARCHAR(255) NOT NULL,
    permanent_residence_district VARCHAR(255) NOT NULL,
    permanent_residence_ward VARCHAR(255) NOT NULL,
    permanent_residence_village VARCHAR(255) NOT NULL,
    permanent_residence_street VARCHAR(255) NOT NULL,
    permanent_residence_postal_box VARCHAR(255) NOT NULL,
    passport_number VARCHAR(255),
    father_national_id VARCHAR(255),
    mother_national_id VARCHAR(255),
    driver_license_number VARCHAR(255),
    voter_registration_number VARCHAR(255),
    health_insurance_number VARCHAR(255),
    tax_identification_number VARCHAR(255),
    zanzibar_resident_id VARCHAR(255),
    social_security_fund_type VARCHAR(255),
    social_security_membership_number VARCHAR(255),
    secondary_education_certificate_number VARCHAR(255),
    higher_secondary_education_certificate_number VARCHAR(255),
    applicant_signature VARCHAR(255) NOT NULL,
    official_use_executive_officer_name VARCHAR(255) NOT NULL,
    official_use_center_number VARCHAR(255) NOT NULL,
    official_use_region VARCHAR(255) NOT NULL,
    official_use_district VARCHAR(255) NOT NULL,
    official_use_ward VARCHAR(255) NOT NULL,
    official_use_center_name VARCHAR(255) NOT NULL,
    application_date DATE NOT NULL,
    registration_officer_name VARCHAR(255) NOT NULL,
    immigration_officer_name VARCHAR(255) NOT NULL,
    rita_rgo_officer_name VARCHAR(255) NOT NULL,
    weo_employer_name VARCHAR(255) NOT NULL,
    nida_officer_name VARCHAR(255) NOT NULL,
    primary_school_name VARCHAR(255) NOT NULL,
    primary_school_district VARCHAR(255) NOT NULL,
    primary_school_graduation_year VARCHAR(255) NOT NULL,
    is_verified BOOLEAN DEFAULT FALSE,
    verification_date DATE,
    metadata JSONB,
    address JSONB NOT NULL,
    email VARCHAR(255),
    place_of_birth VARCHAR(255),
    mother_name VARCHAR(255),
    father_name VARCHAR(255),
    blood_type VARCHAR(50),
    religion VARCHAR(255),
    education_level VARCHAR(255),
    disability_status VARCHAR(50),
    disability_type VARCHAR(255),
    emergency_contact_name VARCHAR(255),
    emergency_contact_phone VARCHAR(255),
    emergency_contact_relationship VARCHAR(255),
    photo_url VARCHAR(255),
    signature_url VARCHAR(255),
    fingerprint_url VARCHAR(255),
    document_url VARCHAR(255),
    verification_status VARCHAR(50),
    verification_notes TEXT,
    registration_date DATE,
    expiry_date DATE,
    last_updated DATE,
    last_updated_by VARCHAR(255),
    status VARCHAR(50),
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create unique index on nida_number
CREATE UNIQUE INDEX idx_nida_number ON nida(nida_number);

-- Create nida_verifications table with foreign key
CREATE TABLE nida_verifications (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    nida_number VARCHAR(255) NOT NULL,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    date_of_birth VARCHAR(255) NOT NULL,
    gender VARCHAR(50) NOT NULL,
    is_valid BOOLEAN NOT NULL,
    match_score DECIMAL(5,2) NOT NULL,
    details JSONB,
    verification_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_nida_verification_nida FOREIGN KEY (nida_number) REFERENCES nida(nida_number) ON DELETE CASCADE
); 