export enum RegistrationStatus {
  PENDING = 'PENDING',
  DOCUMENT_VERIFICATION = 'DOCUMENT_VERIFICATION',
  BIOMETRIC_VERIFICATION = 'BIOMETRIC_VERIFICATION',
  NIDA_VERIFICATION = 'NIDA_VERIFICATION',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED'
} 