export enum Role {
  CITIZEN = 'CITIZEN',
  ADMIN = 'ADMIN',
  SUPER_ADMIN = 'SUPER_ADMIN',
  REGIONAL_ADMIN = 'REGIONAL_ADMIN',
  DISTRICT_ADMIN = 'DISTRICT_ADMIN',
  WARD_ADMIN = 'WARD_ADMIN',
  OFFICE_ADMIN = 'OFFICE_ADMIN',
  REGISTRAR = 'REGISTRAR',
  VERIFIER = 'VERIFIER',
  APPROVER = 'APPROVER',
  VIEWER = 'VIEWER'
} 